package io.pifoo;


import java.io.*;

/**
 * Created by pifoo on 15/11/12.
 * by : http://blog.csdn.net/coder_pig/article/details/48265343
 */
public class Servlet extends javax.servlet.http.HttpServlet {

    public int second = 0;

    protected void doGet(javax.servlet.http.HttpServletRequest request, javax.servlet.http.HttpServletResponse response) throws javax.servlet.ServletException, IOException {
        this.doPost(request,response);




        //case 1: 告诉浏览器响应码，以及重定向页面
        /*response.setStatus(302);
        response.setHeader("Location", "http://www.baidu.com");*/

        //case 2: 返回见面响应信息
        /*response.setContentType("text/html");
        PrintWriter pw = response.getWriter();
        pw.write("<h1> hello first servlet!</h1>");*/

        //case 3: 通过Content-Encoding告诉浏览器数据的压缩格式
        /*String data = "Fresh air and sunshine can have an amazing effect on our feelings. "
                + "Sometimes when we are feeling down, all that we need to do is simply to go "
                + "outside and breathe. Movement and exercise is also a fantastic way to feel better. "
                + "Positive emotions can be generated by motion. So if we start to feel down,"
                + " take some deep breathes, go outside, feel the fresh air, "
                + "let the sun hit our face, go for a hike, a walk, a bike ride, "
                + "a swim, a run, whatever. We will feel better if we do this.";
        System.out.println("原始数据长度:" + data.getBytes().length);
        // 对数据进行压缩:
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        GZIPOutputStream gout = new GZIPOutputStream(bout);
        gout.write(data.getBytes());
        gout.close();
        // 得到压缩后的数据
        byte gdata[] = bout.toByteArray();
        System.out.println("压缩后数据长度:" + gdata.length);
        response.setHeader("Content-Encoding", "gzip");
        response.setHeader("Content-Length", gdata.length + "");
        response.getOutputStream().write(gdata);*/


        //TODO
        //case 3: 通过content-type，设置返回的数据类型
        /*response.setHeader("content-type", "application/pdf");
        InputStream in = this.getServletContext().getResourceAsStream("file/ProAndroid5.pdf");
        byte buffer[] = new byte[1024];
        int len = 0;
        OutputStream out = response.getOutputStream();
        while((len = in.read(buffer)) > 0) {
            out.write(buffer,0,len);
        }*/

        //case 4: 浏览器每隔2秒定时刷新页面
        /*response.setHeader("refresh", "2");
        response.getWriter().write(++second + " ");
        System.out.println("doGet方法被调用~");*/

        //case 5: 进入页面5s后，然页跳到百度~
        /*response.setHeader("refresh", "5;url='http://www.baidu.com'");
        response.getWriter().write("HE HE DA~");*/

        /*
         * http:post,get
         * http://www.imooc.com/video/7214
         */

    }

    protected void doPost(javax.servlet.http.HttpServletRequest request, javax.servlet.http.HttpServletResponse response) throws javax.servlet.ServletException, IOException {
        //this.doGet(request, response);
        /**
         * http:post,get
         * http://www.imooc.com/video/7214
         */
        String name = request.getParameter("name");
        String age = request.getParameter("age");

        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        out.println("name: "+ new String(name.getBytes("iso-8859-1"),"utf-8") + ",age: " + age );//get方式getBytes("iso-8859-1")去掉iso-8859-1参数
        System.out.println("name: "+ new String(name.getBytes("iso-8859-1"),"utf-8") + ",age: " + age );


    }

}
